
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK-Onboarding
    output_directory: build_output
    workspace: GovUK-Onboarding.xcworkspace
    project: Example/GovUK-Onboarding.xcodeproj
    test_plan: Onboarding
  scan:
    devices:
      - iPhone 16 Pro

unit:
  <<: *DEFAULTS
