
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK-Onboarding
    workspace: GovUK-Onboarding.xcworkspace
    project: Example/GovUK-Onboarding.xcodeproj
    test_plan: Onboarding
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.1)

unit:
  <<: *DEFAULTS
